name: PSScriptAnalyzer

on:
  push:
    branches: [main]
    paths:
      - "**/*.ps1"
      - "**/*.psm1"
      - "**/*.psd1"
  pull_request:
    branches: [main]
    paths:
      - "**/*.ps1"
      - "**/*.psm1"
      - "**/*.psd1"
  workflow_dispatch:

permissions:
  contents: read
  security-events: write

jobs:
  psscriptanalyzer:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Run PSScriptAnalyzer
        uses: microsoft/psscriptanalyzer-action@6b2948b1944407914a58661c49941824d149734f # v1.1
        with:
          path: .
          recurse: true
          output: results.sarif

      - name: Upload SARIF results
        uses: github/codeql-action/upload-sarif@b96794f015dfd88f77b49b1c93e0fa7110f94c63 # v4.38.0
        with:
          sarif_file: results.sarif
        if: always()
